name: loc-mode-pred
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.12
  - trackintel
  - pytorch=1.12.1
  - tqdm
  - easydict
  - yaml
  - pyyaml
  - transformers=4.16.2
  - cudatoolkit=11.3
